name: 🐛 Bug
description: Report an issue that should be fixed
labels: [bug]
body:
  - type: input
    attributes:
      label: discord-hono version
      placeholder: 0.0.0
    validations:
      required: true
  - type: textarea
    attributes:
      label: Bug Details
      placeholder: |
        - Steps to reproduce the bug
        - Relevant code examples
        - Expected behavior vs Actual behavior
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Info
