name: 🚀 Idea
description: Suggest an idea, feature, or enhancement
labels: [idea]
body:
  - type: textarea
    attributes:
      label: What is the feature you are proposing?
    validations:
      required: true
